### ISSUE TITLE
Getting Binder working

### ISSUE THREAD

**Issue by choldgraf** [sourceryinstitute/jupyter-CAF-kernel#3]
Hey there - me and @yuvipanda are both devs on the Binder team. We noticed there are a lot of attempts at launching a binder from this repository, but the Docker image isn't prepared correctly to get it working.

Just wanted to let you know about this doc page we put together:

http://mybinder.readthedocs.io/en/latest/dockerfile.html#preparing-your-dockerfile

it covers what conditions need to be met w/ a dockerfile in order for a repository to be compatible with Binder. Just leaving it here in case it's helpful!

**Comment by yuvipanda** [comment]
Specifically, launching it seems to produce the following error message:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1294, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1033, in init_configurables
    connection_dir=self.runtime_dir,
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/conda/lib/python3.6/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local/share/jupyter/runtime'
```

I can't seem to find the Dockerfile that is used to build `FROM sourceryinstitute/jupyter-caf-kernel@sha256:dfe94467325df55a7b83a2bea41b2b40f832229ca5ca92757e49aa866f5f62d8`, so am unsure what the real problem is.

**Comment by zbeekman** [comment]
Hey, thanks for stopping by and pointing me to this resource. I'm guessing the issue is from one of the python packages I'm installing from elsewhere or the base image that I'm building mine from. 

@yuvipanda @choldgraf The image for sourceryinstitute/jupyter-caf-kernel@sha256:dfe94467325df55a7b83a2bea41b2b40f832229ca5ca92757e49aa866f5f62d8 is here: https://github.com/sourceryinstitute/jupyter-CAF-kernel/blob/master/prebuild/Dockerfile

You can find it on docker hub at https://cloud.docker.com/swarm/sourceryinstitute/repository/docker/sourceryinstitute/jupyter-caf-kernel/general

I'll read your new docker docs, but any additional pointers or tips would be most welcome. Thanks!
